### ISSUE TITLE
Max gas 

### ISSUE THREAD

**Issue by MoMannn** [C3Devs/wanmask-extension#9] opened 2019-11-26 12:54 UTC
When creating a transaction, if you do not specify `gas` parameter wanmask will automatically set it. The max it is able to set is `4,476,768` even tho the blockchain limit is actually `4,712,388` at the moment.

**Comment by tyrion70** [comment] 2019-11-28 12:37
I found the cause of this. The gas limit is set to 19/20th of the block max gas. I can't figure out why this was done unfortuately, but I'll make a build to set it to the current max instead of the safer limit::

https://github.com/C3Devs/wanmask-extension/blob/98aa83300efa4d317371129c76ae2df96efbafbf/app/scripts/controllers/transactions/tx-gas-utils.js#L73

**Comment by tyrion70** [comment] 2019-11-29 10:05
WanMask 2.0.3 will be in the chrome store shortly

**Closed** 2019-11-29 10:05 UTC
